FROM maven:3.9.9-eclipse-temurin-17

WORKDIR /workspace

RUN apt-get update && apt-get install -y entr

COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline

# 👇 copiar o script
COPY dev-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080

# 👇 usar exec form
ENTRYPOINT ["/entrypoint.sh"]
